export enum PermissionCode {
  USER_VIEW = 'USER_VIEW',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  BUSINESS_TYPE_VIEW = 'BUSINESS_TYPE_VIEW',    
  BUSINESS_TYPE_CREATE = 'BUSINESS_TYPE_CREATE',
  BUSINESS_TYPE_UPDATE = 'BUSINESS_TYPE_UPDATE', 
  BUSINESS_TYPE_DELETE = 'BUSINESS_TYPE_DELETE',

  DOET_VIEW = 'DOET_VIEW',
  DOET_CREATE = 'DOET_CREATE',
  DOET_UPDATE = 'DOET_UPDATE',
  DOET_DELETE = 'DOET_DELETE',

  INDUSTRY_VIEW = 'INDUSTRY_VIEW',
  INDUSTRY_CREATE = 'INDUSTRY_CREATE',
  INDUSTRY_UPDATE = 'INDUSTRY_UPDATE',
  INDUSTRY_DELETE = 'INDUSTRY_DELETE',

  TRAUMA_FACTOR_CREATE = 'TRAUMA_FACTOR_CREATE',
  TRAUMA_FACTOR_UPDATE = 'TRAUMA_FACTOR_UPDATE',
  TRAUMA_FACTOR_DELETE = 'TRAUMA_FACTOR_DELETE',
  TRAUMA_FACTOR_VIEW = 'TRAUMA_FACTOR_VIEW',

  INJURY_TYPE_CREATE = 'INJURY_TYPE_CREATE',
  INJURY_TYPE_UPDATE = 'INJURY_TYPE_UPDATE',
  INJURY_TYPE_DELETE = 'INJURY_TYPE_DELETE',
  INJURY_TYPE_VIEW = 'INJURY_TYPE_VIEW',

  REPORT_VIEW = 'REPORT_VIEW',
}